"""include quiz session management - include timer for quiz - add a new model(QuizSession)

Revision ID: 72164e79dddc
Revises: 553c71c89182
Create Date: 2025-09-06 14:59:12.620990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72164e79dddc'
down_revision = '553c71c89182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'timeout', 'abandoned', name='session_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_session')
    # ### end Alembic commands ###
